runtime: go119

env_variables:
  GOLANGORG_CHECK_COUNTRY: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: auto

nobuild_files: content/